# type1, type2 are types of actors. Every line is an update to the schema.
# Lines SHOULD NEVER BE REMOVED. If lines are removed new actors will 
#  have an incomplete schema.
# To update the schema add lines for type or add new types.

type1: 
- CREATE TABLE tab (id INTEGER PRIMARY KEY, txt TEXT) 	#version 1
- CREATE TABLE tab1 (id INTEGER PRIMARY KEY, txt TEXT)  #version 2
- ALTER TABLE tab ADD i INTEGER    						#version 3
- CREATE TABLE tabx (id INTEGER PRIMARY KEY, txt TEXT) 	#version 4

type2:
- CREATE TABLE asdf (id INTEGER PRIMARY KEY AUTOINCREMENT, txt BLOB)

# typekv is a key-value type. It will not be an actor but a fragmented table across all nodes
typekv: 
 type: kv
 schema: 
  - CREATE TABLE actors (id TEXT UNIQUE, hash INTEGER, val INTEGER)
