# type1, type2 are types of actors. Every line is an update to the schema.
# Lines SHOULD NEVER BE REMOVED. If lines are removed new actors will 
#  have an incomplete schema.
# To update the schema add lines for type or add new types.

type1: 
- CREATE TABLE tab (id INTEGER PRIMARY KEY, txt TEXT)   #version 1
- ALTER TABLE tab ADD i INTEGER                         #version 2

# typekv is a key-value type. It will not be an actor but a fragmented table across all nodes
typekv: 
 type: kv
 schema: 
  - CREATE TABLE actors (id TEXT UNIQUE, hash INTEGER, val INTEGER)
