# type1 is a type of actor. Every line is an update to the schema.
# Lines SHOULD NEVER BE REMOVED. If lines are removed new actors will 
#  have an incomplete schema.
# To update the schema add lines for type or add new types.

type1: 
- CREATE TABLE tab (id INTEGER PRIMARY KEY, txt TEXT)   #version 1
- ALTER TABLE tab ADD i INTEGER                         #version 2


# counters is a fragmented key value table across all nodes. 
counters: 
 type: kv
 schema: 
  - CREATE TABLE actors (id TEXT UNIQUE, hash INTEGER, val INTEGER)

